services:
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - ./.docker/redis_data:/data

  mongodb:
    image: mongo/mongodb-community-server:latest
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - ./.docker/mongodb:/data/db